In [6]:
#Project Details

# This project works on classifying some zoo animals into certain classes, then evaluating said classification for correctness.

In [8]:
#Library Imports

import pandas as pd # to load the dataset and other similar functionalities.
import numpy as np # for arrays and mathematical calculations.
import matplotlib as plt # for plotting.

In [5]:
#Module Imports

from sklearn.preprocessing import StandardScaler # to scale the features into similar ranges.
from sklearn.neighbors import KNeighborsClassifier # for classification and regression.
from sklearn.model_selection import train_test_split # to split the dataset into 80/20.
from sklearn.metrics import confusion_matrix, f1_score # for evaluation.

In [7]:
#Dataset Exploration

In [13]:
#Dataset Loading

Zoo = pd.read_csv(r'C:\Users\jojos\OneDrive\Pictures\Desktop\DecodeLabs-AI-Internship\Project 2\Zoo Animals Classification Dataset\zoo.csv')

#Displaying the Dataset

Zoo.head()

,animal_name,hair,feathers,eggs,milk,airborne,aquatic,predator,toothed,backbone,breathes,venomous,fins,legs,tail,domestic,catsize,class_type
0,aardvark,1,0,0,1,0,0,1,1,1,1,0,0,4,0,0,1,1
1,antelope,1,0,0,1,0,0,0,1,1,1,0,0,4,1,0,1,1
2,bass,0,0,1,0,0,1,1,1,1,0,0,1,0,1,0,0,4
3,bear,1,0,0,1,0,0,1,1,1,1,0,0,4,0,0,1,1
4,boar,1,0,0,1,0,0,1,1,1,1,0,0,4,1,0,1,1

In [14]:
# As we can see in the tabular display of the first five instances above, the features of the animals are shown in 0s or 1s, where 0 means that this feature is not present in the animal, and 1 means that this feature is present in the animal.

# 'legs' is the only feature that is not in 0s or 1s as it displays the number of legs this animal has.

In [15]:
Zoo.describe()

,hair,feathers,eggs,milk,airborne,aquatic,predator,toothed,backbone,breathes,venomous,fins,legs,tail,domestic,catsize,class_type
count,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000
mean,0.425743,0.198020,0.584158,0.405941,0.237624,0.356436,0.554455,0.603960,0.821782,0.792079,0.079208,0.168317,2.841584,0.742574,0.128713,0.435644,2.831683
std,0.496921,0.400495,0.495325,0.493522,0.427750,0.481335,0.499505,0.491512,0.384605,0.407844,0.271410,0.376013,2.033385,0.439397,0.336552,0.498314,2.102709
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,1.000000
50%,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,4.000000,1.000000,0.000000,0.000000,2.000000
75%,1.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,4.000000,1.000000,0.000000,1.000000,4.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,8.000000,1.000000,1.000000,1.000000,7.000000

In [16]:
Zoo.dtypes

animal_name      str
hair           int64
feathers       int64
eggs           int64
milk           int64
airborne       int64
aquatic        int64
predator       int64
toothed        int64
backbone       int64
breathes       int64
venomous       int64
fins           int64
legs           int64
tail           int64
domestic       int64
catsize        int64
class_type     int64
dtype: object

In [19]:
Zoo.shape

(101, 18)

In [20]:
Zoo.columns

Index(['animal_name', 'hair', 'feathers', 'eggs', 'milk', 'airborne',
       'aquatic', 'predator', 'toothed', 'backbone', 'breathes', 'venomous',
       'fins', 'legs', 'tail', 'domestic', 'catsize', 'class_type'],
      dtype='str')

In [21]:
Zoo.info()

<class 'pandas.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 18 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   animal_name  101 non-null    str
 1   hair         101 non-null    int64
 2   feathers     101 non-null    int64
 3   eggs         101 non-null    int64
 4   milk         101 non-null    int64
 5   airborne     101 non-null    int64
 6   aquatic      101 non-null    int64
 7   predator     101 non-null    int64
 8   toothed      101 non-null    int64
 9   backbone     101 non-null    int64
 10  breathes     101 non-null    int64
 11  venomous     101 non-null    int64
 12  fins         101 non-null    int64
 13  legs         101 non-null    int64
 14  tail         101 non-null    int64
 15  domestic     101 non-null    int64
 16  catsize      101 non-null    int64
 17  class_type   101 non-null    int64
dtypes: int64(17), str(1)
memory usage: 14.9 KB

In [30]:
Mammals = Zoo[Zoo["class_type"] == 1]

Mammals.shape

(41, 18)

In [32]:
Birds = Zoo[Zoo["class_type"] == 2]

Birds.shape

(20, 18)

In [33]:
Reptiles = Zoo[Zoo["class_type"] == 3]

Reptiles.shape

(5, 18)

In [34]:
Fish = Zoo[Zoo["class_type"] == 4]

Fish.shape

(13, 18)

In [35]:
Amphibians = Zoo[Zoo["class_type"] == 5]

Amphibians.shape

(4, 18)

In [36]:
Bugs = Zoo[Zoo["class_type"] == 6]

Bugs.shape

(8, 18)

In [37]:
Invertebrates = Zoo[Zoo["class_type"] ==7]

Invertebrates.shape

(10, 18)

In [38]:
# This shows the numbers of animals in each class:

# Mammals = 41 animals out of 101
# Birds = 20 animals out of 101
# Reptiles = 5 animals out of 101
# Fish = 13 animals out of 101
# Amphibians = 4 animals out of 101
# Bugs = 8 animals out of 101
# Invertebrates = 10 animals out of 101